"""digest/send.py — HTML email formatter and sender."""

import logging
import smtplib
from email.message import EmailMessage

import config

logger = logging.getLogger(__name__)


def send_digest(listings: list[dict]) -> None:
    """
    Build an HTML email digest from *listings* and send it via Gmail SMTP.

    Each listing dict must have at least: title, company, location, url, source.
    Optional key: ethics_flag (str).
    """
    if not listings:
        logger.info("No listings to send — skipping email.")
        return

    html = _build_html(listings)
    plain = _build_plain(listings)

    msg = EmailMessage()
    msg["Subject"] = config.EMAIL_SUBJECT
    msg["From"] = config.EMAIL_FROM
    msg["To"] = config.EMAIL_TO
    msg.set_content(plain)
    msg.add_alternative(html, subtype="html")

    if not config.SMTP_USERNAME or not config.SMTP_PASSWORD:
        raise ValueError(
            "SMTP_USERNAME and SMTP_PASSWORD must be set before sending email. "
            "Set the SMTP_USER and SMTP_PASSWORD environment variables."
        )

    try:
        with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.login(config.SMTP_USERNAME, config.SMTP_PASSWORD)
            smtp.send_message(msg)
        logger.info("Digest sent to %s (%d listings).", config.EMAIL_TO, len(listings))
    except smtplib.SMTPException as exc:
        logger.error("Failed to send digest email: %s", exc)
        raise


# ── HTML helpers ────────────────────────────────────────────────────────────


def _build_html(listings: list[dict]) -> str:
    cards = "\n".join(_listing_card(job) for job in listings)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{config.EMAIL_SUBJECT}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          background: #f4f6f9; margin: 0; padding: 20px; color: #1a1a2e; }}
  .container {{ max-width: 680px; margin: auto; }}
  h1 {{ font-size: 1.6rem; color: #2c3e50; margin-bottom: 4px; }}
  .subtitle {{ color: #6c757d; font-size: 0.9rem; margin-bottom: 24px; }}
  .card {{ background: #fff; border-radius: 10px; padding: 20px 24px;
           margin-bottom: 16px; box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
  .card h2 {{ margin: 0 0 4px; font-size: 1.1rem; }}
  .card h2 a {{ color: #0d6efd; text-decoration: none; }}
  .card h2 a:hover {{ text-decoration: underline; }}
  .meta {{ color: #495057; font-size: 0.88rem; margin-bottom: 8px; }}
  .badge {{ display: inline-block; font-size: 0.75rem; padding: 2px 8px;
            border-radius: 20px; margin-right: 6px; font-weight: 600; }}
  .badge-source {{ background: #e8f4fd; color: #0d6efd; }}
  .flag {{ background: #fff3cd; border-left: 4px solid #ffc107;
           padding: 8px 12px; border-radius: 4px; font-size: 0.85rem;
           color: #856404; margin-top: 10px; }}
  .footer {{ text-align: center; color: #adb5bd; font-size: 0.8rem; margin-top: 32px; }}
</style>
</head>
<body>
<div class="container">
  <h1>{config.EMAIL_SUBJECT}</h1>
  <p class="subtitle">{len(listings)} matching listing{"s" if len(listings) != 1 else ""} found today.</p>
  {cards}
  <p class="footer">Generated by Job Seeker AI Agent 🤖</p>
</div>
</body>
</html>"""


def _listing_card(job: dict) -> str:
    flag_html = ""
    flag = job.get("ethics_flag", "")
    if flag:
        flag_html = f'<div class="flag">⚠️ {_esc(flag)}</div>'

    return (
        '<div class="card">'
        f'<h2><a href="{_esc(job["url"])}">{_esc(job["title"])}</a></h2>'
        f'<div class="meta">'
        f'  <strong>{_esc(job["company"])}</strong>'
        f'  &nbsp;·&nbsp; {_esc(job["location"])}'
        f'</div>'
        f'<span class="badge badge-source">{_esc(job["source"])}</span>'
        f"{flag_html}"
        "</div>"
    )


def _esc(text: str) -> str:
    """Minimal HTML escaping."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


# ── Plain-text fallback ──────────────────────────────────────────────────────


def _build_plain(listings: list[dict]) -> str:
    lines = [f"{config.EMAIL_SUBJECT}", f"{len(listings)} listings found today.", ""]
    for job in listings:
        lines.append(f"{job['title']} — {job['company']}")
        lines.append(f"  Location : {job['location']}")
        lines.append(f"  Source   : {job['source']}")
        lines.append(f"  URL      : {job['url']}")
        flag = job.get("ethics_flag", "")
        if flag:
            lines.append(f"  ⚠️  Flag  : {flag}")
        lines.append("")
    lines.append("Generated by Job Seeker AI Agent 🤖")
    return "\n".join(lines)
